<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
$ip=$_SERVER['SERVER_ADDR'];;
       echo '<p>This content was generated by PHP</p>';
       echo '<p>Server IP is <b>'.$ip.'</b></p>';
?>
<p><img src="./img/google.png" alt="[ img1 ]"></p>
<p>And this content is static HTML</p>
</body>
</html>
