version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./static/:/usr/share/nginx/html/
    networks:
      frontend:
           #  public:
           #         ipv4_address: 192.168.1.241

  php1:
    image: php:7.4-apache
    hostname: php
    volumes:
      - ./dynamic/:/var/www/html
    networks:
      backend:
   
  php2:
    image: php:7.4-apache
    hostname: php
    volumes:
      - ./dynamic/:/var/www/html
    networks:
      backend:
 
      #public:
        #ipv4_address: 192.168.1.242

  haproxy:  
    image: haproxy:2.3 
    container_name: haproxy
    hostname: haproxy
    links: 
      - php1
      - php2
      - web
    volumes:
        - ./cfg/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      backend:
      frontend:
      public:
        ipv4_address: 192.168.1.250
networks:
  backend:
  frontend:  
  public:
    driver: macvlan
    driver_opts:
            parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/28
          gateway: 192.168.1.1
